### ISSUE TITLE
Debug DHHS_IHS

### ISSUE THREAD

**Issue by fsabirinali** [judgelord/correspondence#118]
Changed from getFirstLast to extractMemberName.  There are 427 name errors but most of them are misspellings.
107th and 109th congress only have 3 and 5 data points respectively so that's something to look out for in the future.

**Comment by judgelord** [comment]
Important to correct these spellings #9 

107th and 109th congress are pre-2007, so if the data are really different, we may want to just drop these observations. @rochelle-snyder, any thoughts on how to deal with / note these cases where data in different time periods are systematically different?

**Comment by rochelle-snyder** [comment]
I'm cross-referencing the data in the Google sheet with the original PDF and I think that these dates are just OCR errors. Should I correct them by hand?

**Comment by judgelord** [comment]
Good catch; yes that would be great. We do have a function in `nameMethods.R` to correct OCR errors, so if you see something systematic, I can add it to that function. 

Additionally, these observations had dates that failed to format: 
"collins, susan" x 1: NA
"committee on indian affairs" x 1: NA
"hatch, orrin" x 1: NA
"hoyer, steny" x 1: NA
"inter tribal council of arizona" x 1: NA
"ireland, lorie" x 1: NA
"mcswain, robert" x 1: NA
"tester, jon" x 1: NA
"thunejohn" x 1: NABad dates in NA?
"" x 88: NA
"collins, susan" x 1: NA
"committee on indian affairs" x 1: NA
"hatch, orrin" x 1: NA
"hoyer, steny" x 1: NA
"inter tribal council of arizona" x 1: NA
"ireland, lorie" x 1: NA
"mcswain, robert" x 1: NA
"tester, jon" x 1: NA
"thunejohn" x 1: NA

**Comment by rochelle-snyder** [comment]
The three dates for the 107th Congress (2001-2002) have been fixed by hand; they were all supposed to be 2007. The 109th Congress (2006) dates seem to be correct. It's probably the case that the agency used the date that the correspondence was created in their system to fill our request, meaning that we are also getting correspondence pre-110th Congress that the agency did not start working on until early 2007. How we treat these will depend on whether we want to look at when the letter was written or when the letter was actually handled by the agency.

**Comment by judgelord** [comment]
We have tried to make `DATE` the date the letter was written, so dates received etc. are approximations. If we have any way of estimating the difference between the date we have and the date on the letter, we may consider some across-the-board adjustment to get closer to the date we want. What do you think?

**Comment by rochelle-snyder** [comment]
I think the date we are using is fine - it looks like that's the "incoming date," and the "created date" that they used to create our request is in a separate column. The incoming date is always earlier than the created date, and usually not by much. I'm not sure why there's such a large discrepancy between the two for some letters, but that's why we have a few pre-2007 observations. We could probably drop those if we wanted, as we wouldn't have them in our data if they had used the "incoming date" to create the logs, if that makes sense, but I'll leave that up to you.

**Comment by judgelord** [comment]
Thanks. Yes, the default is that letters with a `DATE` when the member is not in congress are dropped (and the time-series analysis is all post 2007 anyway), but we should be careful that we are not dropping observations incorrectly. Eventually, it may be worth FOIAing some of these letters with "nearly-matching" dates.

**Comment by judgelord** [comment]
A few still failing:
```
row 1209, DATE = NA "collins, susan"
row 1214, DATE = NA "hatch, orrin"
row 1214, DATE = NA "hoyer, steny"
row 1209, DATE = NA "ireland, lorie"
row 1215, DATE = NA "mcswain, robert"
row 1211, DATE = NA "tester, jon"
row 1210, DATE = NA "thune, john"
```
If these are errors, they should be noted as such in the ERROR column
